/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        primary: '#5A413F',
        'primary-foreground': '#ffffff',
        secondary: '#B77767',
        'secondary-foreground': '#ffffff',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: '#B77767',
        'accent-foreground': '#ffffff',
        destructive: 'var(--destructive)',
        'destructive-foreground': 'var(--destructive-foreground)',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',

        /* Admin semantic surface scale — theme-aware via globals.css.
           Use these instead of raw white/zinc/gray so dark mode follows. */
        canvas: 'rgb(var(--admin-canvas) / <alpha-value>)',
        panel: 'rgb(var(--admin-panel) / <alpha-value>)',
        'panel-alt': 'rgb(var(--admin-panel-alt) / <alpha-value>)',
        hairline: 'rgb(var(--admin-hairline) / <alpha-value>)',
        'hairline-soft': 'rgb(var(--admin-hairline-soft) / <alpha-value>)',
        ink: 'rgb(var(--admin-ink) / <alpha-value>)',
        'ink-soft': 'rgb(var(--admin-ink-soft) / <alpha-value>)',
        'ink-muted': 'rgb(var(--admin-ink-muted) / <alpha-value>)',
        brand: 'rgb(var(--admin-brand) / <alpha-value>)',
        'brand-solid': 'rgb(var(--admin-brand-solid) / <alpha-value>)',
        'brand-solid-hover': 'rgb(var(--admin-brand-solid-hover) / <alpha-value>)',
        'on-brand': 'rgb(var(--admin-on-brand) / <alpha-value>)',
        'brand-tint': 'var(--admin-brand-tint)',
        'brand-tint-strong': 'var(--admin-brand-tint-strong)',
        field: 'rgb(var(--admin-field) / <alpha-value>)',
        'row-hover': 'var(--admin-row-hover)',
        'ok-bg': 'rgb(var(--admin-ok-bg) / <alpha-value>)',
        'ok-fg': 'rgb(var(--admin-ok-fg) / <alpha-value>)',
        'warn-bg': 'rgb(var(--admin-warn-bg) / <alpha-value>)',
        'warn-fg': 'rgb(var(--admin-warn-fg) / <alpha-value>)',
        'bad-bg': 'rgb(var(--admin-bad-bg) / <alpha-value>)',
        'bad-fg': 'rgb(var(--admin-bad-fg) / <alpha-value>)',
      },
      boxShadow: {
        panel: 'var(--admin-shadow)',
        lifted: 'var(--admin-shadow-lifted)',
        modal: 'var(--admin-shadow-modal)',
      },
      fontFamily: {
        figtree: ['var(--font-figtree)', 'sans-serif'],
        abhaya: ['var(--font-abhaya)', 'serif'],
      },
    },
  },
  plugins: [],
}
